// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectChangeLog is the predicate function for projectchangelog builders.
type ProjectChangeLog func(*sql.Selector)
